### ISSUE TITLE
 java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.internal.ServiceUtils

### ISSUE THREAD

**Issue by nirby82** [databricks/spark-redshift#103]
I am building a spark project using scala in Intellij. I have added the following dependencies:

spark-redshift_2.10-0.5.1-SNAPSHOT
RedshiftJDBC41-1.1.7.1007
httpcore-4.4.3
httpclient-4.5.1 
aws-java-sdk-s3-1.10.23-SNAPSHOT
aws-java-sdk-core-1.10.23-SNAPSHOT

I am recieving the following error: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.internal.ServiceUtils

where running 
val df = sqlContext.read.foramat("com.databricks.spark.redshift")
.option("url", "jdbc:redshift://AWS_SERVER:5439/warehouse?user=USER&password=PWD")
      .option("dbtable", "fact_time")
      .option("tempdir", "s3n://bucket/path")
      .load()

    df.show()

**Comment by JoshRosen** [comment]
Hi @nirby82, is there more of the stack trace that you could post?

**Comment by nirby82** [comment]
here is the rest of the exception

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.internal.ServiceUtils
	at com.amazonaws.services.s3.internal.S3Signer.sign(S3Signer.java:168)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:709)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3604)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3557)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketLifecycleConfiguration(AmazonS3Client.java:1905)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketLifecycleConfiguration(AmazonS3Client.java:1892)
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:78)
	at com.databricks.spark.redshift.RedshiftRelation.buildScan(RedshiftRelation.scala:77)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:53)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:53)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:279)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:278)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:310)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:274)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:49)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:374)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:920)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:918)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:924)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:924)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:53)
	at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:1904)
	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1385)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1315)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1378)
	at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:178)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:402)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:363)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:371)
	at Testing$.main(Testing.scala:33)
	at Testing.main(Testing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
15/10/05 12:42:52 INFO SparkContext: Invoking stop() from shutdown hook

**Comment by JoshRosen** [comment]
How are you managing your project's dependencies? If you're not using Maven or SBT then my guess is that you're somehow missing one of the AWS libraries' transitive dependencies.

**Comment by nirby82** [comment]
com.amazonaws.services.s3.internal.ServiceUtils is part of the aws-java-s3 library which i have included it in the project. I am using intellij, and including the libraries needed as jar files in the project

**Comment by JoshRosen** [comment]
Based on the stacktrace, my hunch is that this is being caused by an exception in the `com.amazonaws.services.s3.internal.ServiceUtils` class's static initialization code. According to http://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core/1.10.22, `aws-java-sdk-core` has additional dependencies which you have not included in your project. Can you try including an appropriate version of `joda-time` and `commons-logging` to see if that fixes things?

My hunch is that ServiceUtils is trying to call a DateUtils method via its static initializer, which is failing due to missing `joda-time` classes.

**Comment by nirby82** [comment]
I have added joda-time and jackson_databind and it is working now :) I am receiving a redshift error about the bucket, but that is an error I am familiar with that requires the bucket to be in the same region as the redshift cluster, so we will create one like that. thanks!

**Comment by JoshRosen** [comment]
Glad to hear that you were able to get things working!

In the future, I'd like to relax the requirement that the S3 bucket and Redshift cluster belong to the same region; please follow #87 to track progress on that issue.
