### ISSUE TITLE
An error occurred while trying to read the S3 bucket lifecycle configuration

### ISSUE THREAD

**Issue by hafizmujadid** [databricks/spark-redshift#121]
Hi !

I am trying to load data from a redshift table but unable to do so.
here is my code 
              val conf = new SparkConf().setAppName("TestApp").setMaster("local[*]")
		val sc = new SparkContext(conf)
		val sqlContext = new SQLContext(sc)
		val df1: DataFrame = sqlContext.read
			.format("com.databricks.spark.redshift")
			.option("url", "jdbc:redshift://host.us-east-1.redshift.amazonaws.com:5439/test?user=uname&password=pwd")
			.option("dbtable", "users")
			.option("tempdir", "s3n://accesskey:secretkey@redhsift-storage/test")
			.load()
		df1.show()

I get following exception

WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
java.lang.NullPointerException
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:76)
	at com.databricks.spark.redshift.RedshiftRelation.buildScan(RedshiftRelation.scala:76)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:266)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:265)
	at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:296)
	at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:261)
	at org.apache.spark.sql.sources.DataSourceStrategy$.apply(DataSourceStrategy.scala:46)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:314)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:943)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:941)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:947)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:947)
	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1269)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1203)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1262)
	at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:176)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:331)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:338)
	at test.TestClass$.main(TestClass.scala:21)
	at test.TestClass.main(TestClass.scala)
Exception in thread "main" java.net.URISyntaxException: Relative path in absolute URI: s3n://redhsift-storage%5Ctest%5Cf19a1019-5b20-41e5-a8df-b6490426eb64
	at java.net.URI.checkPath(URI.java:1804)
	at java.net.URI.<init>(URI.java:679)
	at java.net.URI.<init>(URI.java:781)
	at com.databricks.spark.redshift.Utils$.joinUrls(Utils.scala:47)
	at com.databricks.spark.redshift.Utils$.makeTempPath(Utils.scala:61)
	at com.databricks.spark.redshift.Parameters$MergedParameters.createPerQueryTempDir(Parameters.scala:78)
	at com.databricks.spark.redshift.RedshiftRelation.buildScan(RedshiftRelation.scala:100)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:50)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:266)
	at org.apache.spark.sql.sources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:265)
	at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:296)
	at org.apache.spark.sql.sources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:261)
	at org.apache.spark.sql.sources.DataSourceStrategy$.apply(DataSourceStrategy.scala:46)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:54)
	at org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:314)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:943)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:941)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:947)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:947)
	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1269)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1203)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1262)
	at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:176)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:331)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:338)

Any suggestion?

thanks

**Comment by hafizmujadid** [comment]
The bucket is in US standard region and redshift cluster is in us east region.

**Comment by JoshRosen** [comment]
Based on some of the line numbers in your exceptions, it looks like you might be using an older version of this library. Which version are you using? Can you try using version 0.5.2 (the newest version) first to see whether that happens to fix this problem?

**Comment by hafizmujadid** [comment]
Yes the above exception is absent now, but having issue with jackson liberary. 
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'id' (in class org.apache.spark.rdd.RDDOperationScope)
 at [Source: {"id":"0","name":"newAPIHadoopFile"}; line: 1, column: 1]

I am using spark 1.4.0 which version should i use for jackson?

**Comment by hafizmujadid** [comment]
Thanks Josh!

I am using spark 1.4.1 version with aws-java-sdk-s3 and aws-java-sdk-code
having version 1.10.22, this combination is creating conflict for jackson
library spark has 2.4.4 and aws-java-sdk-core has 2.5.3. So i am facing
this issue

 com.fasterxml.jackson.databind.JsonMappingException: Could not find
creator property with name 'id' (in class
org.apache.spark.rdd.RDDOperationScope)


Any guidance?


On Thu, Nov 12, 2015 at 7:45 PM, Josh Rosen <notifications@github.com>
wrote:

> Based on some of the line numbers in your exceptions, it looks like you
> might be using an older version of this library. Which version are you
> using? Can you try using version 0.5.2 (the newest version) first to see
> whether that happens to fix this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/databricks/spark-redshift/issues/121#issuecomment-156122077>
> .
>



-- 
Regards: HAFIZ MUJADID

**Comment by hafizmujadid** [comment]
resolved issue by adding jackson library with latest 2.6 version
