### ISSUE TITLE
Warning: An error occurred while trying to read the S3 bucket lifecycle configuration

### ISSUE THREAD

**Issue by wangchuan3533** [databricks/spark-redshift#138]
```
15/12/24 10:46:47 WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
java.lang.NullPointerException
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:94)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:368)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
	at $line22.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:22)
	at $line22.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:27)
	at $line22.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:29)
	at $line22.$read$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:31)
	at $line22.$read$$iwC$$iwC$$iwC$$iwC.<init>(<console>:33)
	at $line22.$read$$iwC$$iwC$$iwC.<init>(<console>:35)
	at $line22.$read$$iwC$$iwC.<init>(<console>:37)
	at $line22.$read$$iwC.<init>(<console>:39)
	at $line22.$read.<init>(<console>:41)
	at $line22.$read$.<init>(<console>:45)
	at $line22.$read$.<clinit>(<console>)
	at $line22.$eval$.<init>(<console>:7)
	at $line22.$eval$.<clinit>(<console>)
	at $line22.$eval.$print(<console>)
```

**Comment by JoshRosen** [comment]
It looks like this is throwing a NPE because `S3Client.getBucketLifecycleConfiguration` returned `null`, which can happen ["if the specified bucket does not exist."](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getBucketLifecycleConfiguration(java.lang.String)). I'll submit a patch so that we correctly handle this case and log a less confusing warning message.

How did you hit this error? Were you passing a non-existent bucket?

**Comment by JoshRosen** [comment]
In #142, I added logic to print a nicer error-message for non-existent buckets.

I'm going to speculatively mark this issue as "resolved" for now, but please comment here and re-open if this error occurs in a situation where the bucket does exist or if you have more information on your original bug report. Thanks!

**Comment by wangchuan3533** [comment]
I'm sorry for my late reply, and thank you for replying.
> How did you hit this error? 
I hit this **warning** when using spark-shell, it dose not stop the loading process.
> Were you passing a non-existent bucket?
no, the bucket exists, and the loading success.

**Comment by kelleyrw** [comment]
I'm still seeing this issue in Spark 2.2.0 -- any updates?

`17/08/02 10:21:15 WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
java.lang.NullPointerException
	at java.lang.String.startsWith(String.java:1405)
	at java.lang.String.startsWith(String.java:1434)
	at com.databricks.spark.redshift.Utils$$anonfun$5.apply(Utils.scala:140)
	at com.databricks.spark.redshift.Utils$$anonfun$5.apply(Utils.scala:136)
	at scala.collection.Iterator$class.exists(Iterator.scala:919)
	at scala.collection.AbstractIterator.exists(Iterator.scala:1336)
	at scala.collection.IterableLike$class.exists(IterableLike.scala:77)
	at scala.collection.AbstractIterable.exists(Iterable.scala:54)
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:136)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:389)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:108)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConne`

**Comment by vnktsh** [comment]
I was able to silence this by setting this piece of code's logger to ERROR

```
import org.apache.log4j.{Level, Logger}

// insert this line after spark session initiation
Logger.getLogger("com.databricks.spark.redshift.Utils$").setLevel(Level.ERROR)
```
