### ISSUE TITLE
ClassNotFoundException: com.databricks.spark.redshift.DefaultSource

### ISSUE THREAD

**Issue by mukundrv** [databricks/spark-redshift#140]
I started spark

```
 sudo bin/spark-shell  --packages com.databricks:spark-redshift_2.10:0.5.2
```

I submitted a job

```
sudo ~/spark/spark-1.5.2/bin/spark-submit --class "SparkRedshiftTutorial" --master local[4] target/scala-2.11/simple-project_2.11-1.0.jar 
```

I am getting the following error: 

```
Exception in thread "main" java.lang.ClassNotFoundException: Failed to load class for data source: com.databricks.spark.redshift.
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:67)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:87)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at SparkRedshiftTutorial$.main(SparkRedshiftTutorial.scala:36)
	at SparkRedshiftTutorial.main(SparkRedshiftTutorial.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.redshift.DefaultSource
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
	at scala.util.Try.orElse(Try.scala:82)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:60)
	... 13 more
```

Is there anything else to be done?

**Comment by JoshRosen** [comment]
Your `spark-shell` and `spark-submit` invocations are completely independent, so the `--packages` flag that you passed to the first `spark-shell` command did not affect the classpath / dependencies of your actual job submission via `spark-submit`. You'll need to pass `--packages` as part of your `spark-submit` call or configure your build tool to package those classes into the JAR that you pass to `spark-submit`.
