### ISSUE TITLE
[Amazon](500150) Error setting/closing connection: Connection timed out.

### ISSUE THREAD

**Issue by ullasjain21** [databricks/spark-redshift#160]
```
java.sql.SQLException: [Amazon](500150) Error setting/closing connection: Connection timed out.
	at com.amazon.redshift.client.PGClient.connect(Unknown Source)
	at com.amazon.redshift.client.PGClient.<init>(Unknown Source)
	at com.amazon.redshift.core.PGJDBCConnection.connect(Unknown Source)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at com.helpchat.Docs.getData(Docs.java:47)
Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: Connection timed out.
	... 8 more
Caused by: java.net.ConnectException: Connection timed out
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:484)
	at sun.nio.ch.Net.connect(Net.java:476)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:675)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:98)
	at com.amazon.redshift.client.PGClient.connect(Unknown Source)
	at com.amazon.redshift.client.PGClient.<init>(Unknown Source)
	at com.amazon.redshift.core.PGJDBCConnection.connect(Unknown Source)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at com.helpchat.Docs.getData(Docs.java:47)
	at com.helpchat.Docs.main(Docs.java:28)
```

**Comment by JoshRosen** [comment]
This looks similar to #148. My hunch is that there's some sort of connectivity issue between your driver and Redshift cluster. Did you configure your security groups in order to allow traffic between the driver and Redshift?

**Comment by JoshRosen** [comment]
Hi @ullasjain21, do you have any updates here? I'm going to resolve this issue as "stale / awaiting update" for now and will re-open if you provide additional information to help with troubleshooting.

**Comment by chuxolatouz** [comment]
Hi @ullasjain21  I don't know if you solved this, but i had the same issue and i fixed it adding a new CIDR/IP connection type in Security Groups of Redshift console in AWS with my IP address

**Comment by prasadpande1990** [comment]
Hi,

I have followed these instructions I have added new rule to the EC2 security group and used that while creating the redshift cluster but I am still getting the same error.

One thing I observed is that in Redshift -> Security Groups I don't have option to create new security group it says -

Your account does not support the EC2-Classic Platform in this region. Cluster Security Groups are only available when the EC2-Classic Platform is supported. Instead, use VPC Security Groups to control access to your clusters. Go to the EC2 Console to view your VPC Security Groups. For more information, see Amazon Redshift Documentation on Supported Platforms and Managing Clusters in VPC.

I configure the security group at EC2 still having same issue.

Can somebody help me?

**Comment by thanhpham310** [comment]
Sign-in into AWS Console
1. Go into EC2 Management Console
2. On the left navigation pane, look for Network & Security header and click on Security Groups. (https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroups:sort=groupId)
3. Notice the row with "Default" and "launch-wizard-1" in the Group Name's column. Click those. Then select the Inbound tab, and click Edit.
4. Add Rule: Type=Redshift, Source=MyIP. (auto-fill)
5. Save it.
6. Try to connect again from within SQLWorkbench/J. Feel good!

**Comment by uanaidu** [comment]
Its working by following above steps.  Thanks for your solution :)

**Comment by en-pratibha** [comment]
Yes, its working by above solution, Thanks.

**Comment by vikaskpathak** [comment]
It worked for me when I added "?ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory" the end of URL.
https://blog.openbridge.com/definitive-guide-for-connecting-sql-workbench-j-to-amazon-redshift-57d06aa32805
