### ISSUE TITLE
Thread safety of spark-redshift lib under Pyspark? 

### ISSUE THREAD

**Issue by ctweney** [databricks/spark-redshift#161]
I have a use case where I need to load batches of data, transform them, and then save the batches to Redshift. The data loading/transformation happens on the Spark workers. The Redshift-saving happens on the driver, obviously, which I noticed blocks for the entire time that the Redshift cluster is processing the COPY commands. This means the whole cluster is stuck doing nothing while the driver waits on Redshift. This seems inefficient. 

I got the idea to speed the chunks up by doing the Redshift-save asynchronously:

```
import asyncio
loop = asyncio.get_event_loop()
loop.run_in_executor(None, self.sql_context.sql(...).write.format("com.databricks.spark.redshift").save())
```

Then the Spark driver can wait for sql_context.save() to return while it goes on sending another loop of the data batches to the workers.

The code does seem to work in my tests. My question is, is this safe? Does spark-redshift and/or sql_context's save() account properly for threaded use cases? 

I'm using spark-redshift 0.5.2 on Spark 1.5.2, Python 3.5.1, all under EMR 4.2.0, if it makes any difference.

**Comment by emlyn** [comment]
We have a similar use case, and had the same idea, but were unable to get it to work. We're using the Spark Java API (on Spark 1.6.0) from Clojure, and tried doing something like:
```Clojure
(let [jobs (mapv #(future (.. % write (options ...) (format "com.databricks.spark.redshift") save))
                 dataframes]
  (mapv deref jobs))
```
But when this runs, Spark fails with a TimeoutException (see stack trace below). But I'm not sure if it's because we're doing something wrong, or there's something inherently unsafe about this.

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Futures timed out after [300 seconds] 
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) 
... 
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731) 
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181) 
... 
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [300 seconds] 
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) 
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) 
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107) 
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) 
        at scala.concurrent.Await$.result(package.scala:107) 
        at org.apache.spark.sql.execution.joins.BroadcastHashOuterJoin.doExecute(BroadcastHashOuterJoin.scala:113) 
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132) 
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130) 
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150) 
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130) 
        at org.apache.spark.sql.execution.Project.doExecute(basicOperators.scala:46) 
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132) 
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130) 
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150) 
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130) 
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55) 
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55) 
        at org.apache.spark.sql.DataFrame.rdd$lzycompute(DataFrame.scala:1676) 
        at org.apache.spark.sql.DataFrame.rdd(DataFrame.scala:1673) 
        at org.apache.spark.sql.DataFrame.mapPartitions(DataFrame.scala:1465) 
        at com.databricks.spark.redshift.RedshiftWriter.unloadData(RedshiftWriter.scala:264) 
        at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:374) 
        at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106) 
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222) 
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148) 
```

**Comment by JoshRosen** [comment]
`spark-redshift` is designed to be thread-safe; independent queries will use completely different sets of temporary files in S3, different JDBC connections, etc., so they shouldn't conflict with one another.

@ctweney, could you clarify what you mean when you say that this doesn't seem to work in your test cases? What do you expect to happen? What actually happens? It would be good to understand whether it's just freezing and not completing the save vs. giving wrong / unexpected output.

@emlyn, Spark is designed to be thread-safe and support concurrent jobs. I'm wondering whether you might be seeing those timeouts due to some sort of thread-pool exhaustion. @zsxwing, have you seen this type of timeout before? Any ideas for next steps in investigation?

**Comment by ctweney** [comment]
It works in my tests. I've run a number of jobs now using this strategy
without error. I just wanted to make sure it wouldn't void my warranty, so
to speak. Glad to hear it is threadsafe.

**Comment by emlyn** [comment]
As it's working for others, there's probably something wrong with the way we're doing it, I'll try to put together a minimal test case.

**Comment by JoshRosen** [comment]
Sounds good. I'm going to close out this issue for now, but let's open a new one for @emlyn's issue once we have more information; thanks!

**Comment by emlyn** [comment]
Just in case anyone else has the same error as I did and stumbles onto this thread - in my case it was fixed by increasing `spark.sql.broadcastTimeout` to `9000` (15 mins).
