### ISSUE TITLE
S3N PermanentRedirect issue

### ISSUE THREAD

**Issue by lc0** [databricks/spark-redshift#176]
First of all thanks for the nice package! 

Unfortunately, I have some issues with using it. So I have a simple SQLContext with tempdir based on S3N

```python
df = sql_context.read \
    .format("com.databricks.spark.redshift") \
    .option("url", "jdbc:redshift://node:5439/production?user=user&password=pass") \
    .option("query", "select data from table") \
    .option("tempdir", "s3n://here.ismy.bucket/spark") \
    .load()
```

it works, when I do `df.count()`, but fails if I do `df.show()`

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/Cellar/apache-spark/1.6.0/libexec/python/pyspark/sql/dataframe.py", line 257, in show
    print(self._jdf.showString(n, truncate))
  File "/usr/local/Cellar/apache-spark/1.6.0/libexec/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/local/Cellar/apache-spark/1.6.0/libexec/python/pyspark/sql/utils.py", line 45, in deco
    return f(*a, **kw)
  File "/usr/local/Cellar/apache-spark/1.6.0/libexec/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o2023.showString.
: java.sql.SQLException: [Amazon](500310) Invalid operation: S3ServiceException:The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.,Status 301,Error PermanentRedirect,Rid id,ExtRid eWEWEW/LpIKg
Details:
 -----------------------------------------------
  error:  S3ServiceException:The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.,Status 301,Error PermanentRedirect,Rid id,ExtRid eWEWEW/LpIKg
  code:      8001
  context:   Listing bucket=here.ismy.bucket prefix=spark/e435512f-784d-4df3-99b7-e37cb0dd2367/
  query:     0
  location:  s3_unloader.cpp:185
  process:   padbmaster [pid=20493]
  -----------------------------------------------;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getReadyForQuery(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGClient.executePreparedStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.executePreparedStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:122)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:122)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$2.apply(RedshiftJDBCWrapper.scala:140)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: S3ServiceException:The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.,Status 301,Error PermanentRedirect,Rid id,ExtRid eWEWEW/LpIKg
Details:
 -----------------------------------------------
  error:  S3ServiceException:The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.,Status 301,Error PermanentRedirect,Rid id,ExtRid eWEWEW/LpIKg
  code:      8001
  context:   Listing bucket=here.ismy.bucket prefix=spark/e435512f-784d-4df3-99b7-e37cb0dd2367/
  query:     0
  location:  s3_unloader.cpp:185
  process:   padbmaster [pid=20493]
  -----------------------------------------------;
	... 27 more
```

I also tried to configure endpoint, but not sure what is the proper format for that.
```
sc._jsc.hadoopConfiguration().set("fs.s3n.endpoint", "s3-eu-west-1.amazonaws.com")
```

**Comment by JoshRosen** [comment]
The reason that this works for `count()` but not for `show()` is that `spark-redshift` will not `UNLOAD` rows to S3 if the `UNLOAD` would return rows with zero columns; this is the case for `count()` queries. The `show()` query, on the other hand, actually needs to fetch rows from Redshift thus involves data transfer to S3.

In this case, the error is coming from Redshift itself, not the S3N Hadoop FileSystem, which is why setting `fs.s3n.endpoint` won't make any difference here. Five minutes of Googling suggests that this particular Redshift error can occur if your Redshift cluster and S3 bucket are in different regions:  https://stackoverflow.com/questions/24860468/amazon-redshift-copy-command

Redshift allows you to do cross-region `COPY` but not `UNLOAD`; see https://github.com/databricks/spark-redshift/issues/87#issuecomment-174732353 for more details.

Are your Redshift cluster and S3 bucket in different regions?

**Comment by lc0** [comment]
yeah, just found the same answer. Thanks for your help!

Yes, my test bucket was in a different region. My correct bucket should be in Frankfurt and seems like there is another issue with Frankfurt region, where ASW has Signature Version 4

and my current error is 

```
py4j.protocol.Py4JJavaError: An error occurred while calling o805.showString.
: java.io.IOException: s3n://fra.ismy.bucket/spark : 400 : Bad Request
````

**Comment by lc0** [comment]
the spark I use is `spark-assembly-1.6.0-hadoop2.6.0.jar`

**Comment by JoshRosen** [comment]
I think that you'll need to use a newer version of Jets3t; see https://issues.apache.org/jira/browse/SPARK-11353

**Comment by JoshRosen** [comment]
I'm going to go ahead and close this issue now because I don't think that this is an issue that is addressable in `spark-redshift` itself.
