### ISSUE TITLE
Error while using spark compiled with hadoop 1.0.4

### ISSUE THREAD

**Issue by cdriesch** [databricks/spark-redshift#180]
We are using a DataStax Enterprise node, that it is based on hadoop 1.0.4. So far, there is no possibility to upgrade to hadoop 2. We are using version 0.5.0 of spark-redshift. When we want to write a dataframe to redshift, an error occurs since spark-redshift is compiled with hadoop 2. Is there a solution to this problem? 

Stacktrace: 

```
**java.lang.IncompatibleClassChangeError: Found class org.apache.hadoop.mapreduce.TaskAttemptContext, but interface was expected
	at org.apache.avro.mapreduce.AvroKeyOutputFormat.getRecordWriter(AvroKeyOutputFormat.java:88)
	at com.databricks.spark.avro.AvroOutputWriter.<init>(AvroOutputWriter.scala:82)
	at com.databricks.spark.avro.AvroOutputWriterFactory.newInstance(AvroOutputWriterFactory.scala:31)
	at org.apache.spark.sql.sources.DefaultWriterContainer.initWriters(commands.scala:470)
	at org.apache.spark.sql.sources.BaseWriterContainer.executorSideSetup(commands.scala:360)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation.org$apache$spark$sql$sources$InsertIntoHadoopFsRelation$$writeRows$1(commands.scala:172)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation$$anonfun$insert$1.apply(commands.scala:160)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation$$anonfun$insert$1.apply(commands.scala:160)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdriesch** [comment]
We also tried with spark-redshift versions 0.6.0 and 0.5.2. The result was the same unfortunately.

**Comment by JoshRosen** [comment]
Although the `spark-redshift` library is compiled against Hadoop 2, it uses reflection whenever it accesses Hadoop methods which are binary-incompatible between 1.x and 2.x (such as TaskAttemptContext.getConfiguration). The problem that you're seeing has to do with the wrong version of [`avro-mapred`](http://mvnrepository.com/artifact/org.apache.avro/avro-mapred) being used, since that's where the exception is being thrown from, and is not actually an issue with `spark-redshift` itself.

`spark-avro` doesn't directly depend on `avro-mapred` but, rather, declares it as a provided dependency and assumes that your Hadoop distribution will provide the correct dependency.

In your shoes, I'd try to figure out which dependency or JAR is providing the `org.apache.avro.mapreduce.AvroKeyOutputFormat` class and override / replace that dependency so that you depend on a version of the library with the `hadoop1` classifier. One way to do this might be to add an explicit dependency on `avro-mapred` to your build file. Assuming SBT:

```
libraryDependencies += "org.apache.avro" % "avro-mapred" % "1.7.7" classifier "hadoop1"
```
