### ISSUE TITLE
Creating table in non-public schema doesn't work

### ISSUE THREAD

**Issue by ctweney** [databricks/spark-redshift#193]
According to comments on #125 it's supposed to be possible to write data to a table that's in a non-default db schema, by passing e.g. dbtable="foo.bar". When I try this, however, I get an exception:

```
  File "/Users/chris/spark-1.5.2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
  File "/Users/chris/spark-1.5.2/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o115.sql.
: org.apache.spark.sql.AnalysisException: Specifying database name or other qualifiers are not allowed for temporary tables. If the table name has dots (.) in it, please quote the table name with backticks (`).;
	at org.apache.spark.sql.catalyst.analysis.Catalog$class.checkTableIdentifier(Catalog.scala:97)
	at org.apache.spark.sql.catalyst.analysis.SimpleCatalog.checkTableIdentifier(Catalog.scala:104)
	at org.apache.spark.sql.catalyst.analysis.SimpleCatalog.lookupRelation(Catalog.scala:134)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.getTable(Analyzer.scala:257)
```

If I quote the tablename with backticks, it's going to be created in the public schema, which isn't right.

**Comment by JoshRosen** [comment]
Are you using a `SQLContext` or `HiveContext`? It looks like the latter might be needed for this to work: https://stackoverflow.com/questions/33221092/need-to-access-hive-table-using-database-qualifier-from-spark
