### ISSUE TITLE
Connection failure affects all follow-on operations in REPL session

### ISSUE THREAD

**Issue by ssimeonov** [databricks/spark-redshift#212]
If Redshift closes the connection, execution state is not cleaned up well because every other attempt to use `spark-redshift` in the same REPL session results in a connection timeout error. Meanwhile, other REPL sessions have no problem connecting to Redshift. 

Here is an example error that leads to this behavior:

```
java.sql.SQLException: [Amazon][JDBC](10060) Connection has been closed.
	at com.amazon.jdbc.communications.InboundMessagesThread.close(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesThread.run(Unknown Source)
Caused by: com.amazon.jdbc.communications.exceptions.InboundErrorMessage: [Amazon][JDBC](10060) Connection has been closed.
	at com.amazon.jdbc.communications.InboundMessagesThread.close(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesThread.run(Unknown Source)
```

I have observed this problem consistently in the Databricks environment but I cannot reproduce it locally doing simple things like breaking the network connection to Redshift.

I am using the Redshift JDBC driver.

**Comment by JoshRosen** [comment]
Do you still observe this issue? I'm going to close this issue as unreproducible for now, but please comment if you see this again.
