### ISSUE TITLE
Saving a nested JSON to redshift

### ISSUE THREAD

**Issue by samelamin** [databricks/spark-redshift#231]
Seems like saving a nested json fails because of the structure, are you aware of this problem?

is there not a way to create tables based on the nested json given a primary key?

**Comment by JoshRosen** [comment]
If by "nested JOSN" you mean that you read nested JSON data into a Spark SQL DataFrame then tried to save the resulting DF to Redshift, my understanding is that Redshift doesn't support nested fields to the same degree that Spark does, so the `spark-redshift` connector won't be able to figure out how to map your Spark schema into something that Redshift understands. If you got a stacktrace / exception when trying this, do you mind posting it here so that this issue is easier to find?

What you might be able to do is to use a Spark SQL function to convert columns with nested data into JSON strings and then save those strings back to Redshift; once you have JSON in Redshift, you can query it with [Redshift's built-in JSON functions](https://docs.aws.amazon.com/redshift/latest/dg/json-functions.html) (although this might be slow).

**Comment by samelamin** [comment]
Ok I will try that


FYI below is part of the stack trace 

Exception in thread "main" java.lang.IllegalArgumentException: Don't know how to save StructField(blah,StructType(StructField(blah,StructType(StructField(ApplicationNaStructField(foo,BooleanType,true)),true)),true) to JDBC
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$schemaString$1.apply(RedshiftJDBCWrapper.scala:262)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$schemaString$1.apply(RedshiftJDBCWrapper.scala:242)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.databricks.spark.redshift.JDBCWrapper.schemaString(RedshiftJDBCWrapper.scala:242)
	at com.databricks.spark.redshift.RedshiftWriter.createTableSql(RedshiftWriter.scala:75)
	at com.databricks.spark.redshift.RedshiftWriter.com$databricks$spark$redshift$RedshiftWriter$$doRedshiftLoad(RedshiftWriter.scala:160)
	at com.databricks.spark.redshift.RedshiftWriter$$anonfun$saveToRedshift$1.apply(RedshiftWriter.scala:378)
	at com.databricks.spark.redshift.RedshiftWriter$$anonfun$saveToRedshift$1.apply(RedshiftWriter.scala:376)
	at com.databricks.spark.redshift.RedshiftWriter.withStagingTable(RedshiftWriter.scala:121)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:376)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)

**Comment by JoshRosen** [comment]
Yep, exactly as I thought. We should add a more helpful error message when we discover that a user is tying to save a nested StructType field, perhaps linking to this issue or a page with workarounds.

**Comment by samelamin** [comment]
perfect thanks @JoshRosen  as a first go im going to save the entire blob as a string to redshift. Then work on breaking things down and joining them

But ideally it should just be an extention method, because there will be so many people dealing with jsons

**Comment by samelamin** [comment]
FYI I feel like writing up my workaround for this issue, given this nested json below

```
{"OrderContainer":{"BasketInfo":{"BasketId":"kjOIxlJFc0WYdQXm2AXksg","MenuId":119949,"Items":[{"ProductId":12310,"UnitPrice":5.5,"foo":[1,2,3],"bar":["a","b","c"]},{"ProductId":456323,"UnitPrice":5.5,"foo":[1,2,3],"bar":["a","b","c"]},{"ProductId":23432432,"UnitPrice":5.5,"foo":[1,2,3],"bar":["a","b","c"]}]}}}
```


What I have done is explode the items into an array below 

```
    val basketItems = df.select($"OrderContainer.BasketInfo.BasketId",
      $"OrderContainer.BasketInfo.MenuId",
      explode($"OrderContainer.BasketInfo.Items")).toDF("BasketId","MenuId","Items")
```


I am just missing the final part which is to convert the foo and bar columns into strings so i can save to redshift  Any Ideas?

**Comment by samelamin** [comment]
FYI I solved it by creating a function to make the array a string

```
val mkString = udf((a: Seq[Any]) => a.mkString(","))
```

Make sure to import the udf function

Then all you have to use is the withColumn function
```
.withColumn("foo", mkString($"foo"))
```
