### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Could not load an Amazon Redshift JDBC driver

### ISSUE THREAD

**Issue by robbyki** [databricks/spark-redshift#233]
Trying to run the below in Intellij (without using spark-submit and adding the jdbc postgres jar file with --jars flag). I have the below basic code to test out a connection to redshift but getting the below error. 

```
import org.apache.spark.sql._
import org.apache.spark.sql.SQLContext
import org.apache.spark.{SparkConf, SparkContext}
object RedshiftTest {
  def main(args: Array[String]) {
    val sparkConf = new SparkConf().setAppName("Test").setMaster("local[*]")
    val sc = new SparkContext(sparkConf)
    val sqlContext = new SQLContext(sc)
    val jdbcURL = "jdbc:redshift://<host>:5439/<db>?user=<username>&password=<pass>"
    val tempS3Dir = "s3a://<bucket>/spark_redshift_out/"
    val hadoopConf =sc.hadoopConfiguration
    hadoopConf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
    hadoopConf.set("fs.s3a.awsAccessKeyId", "<key>")
    hadoopConf.set("fs.s3a.awsSecretAccessKey", "<secret>")

    // Get some data from a Redshift table
    val df: DataFrame = sqlContext.read
      .format("com.databricks.spark.redshift")
      .option("url", jdbcURL)
      .option("dbtable", "<table>")
      .option("tempdir", tempS3Dir)
      .load()

    println(df.show())

}

Exception in thread "main" java.lang.ClassNotFoundException: Could not load an Amazon Redshift JDBC driver; see the README for instructions on downloading and configuring the official Amazon driver.
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$getDriverClass$1.apply(RedshiftJDBCWrapper.scala:80)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$getDriverClass$1.apply(RedshiftJDBCWrapper.scala:70)
	at scala.Option.getOrElse(Option.scala:121)
	at com.databricks.spark.redshift.JDBCWrapper.getDriverClass(RedshiftJDBCWrapper.scala:69)
	at com.databricks.spark.redshift.JDBCWrapper.getConnector(RedshiftJDBCWrapper.scala:205)
	at com.databricks.spark.redshift.RedshiftRelation$$anonfun$schema$1.apply(RedshiftRelation.scala:63)
	at com.databricks.spark.redshift.RedshiftRelation$$anonfun$schema$1.apply(RedshiftRelation.scala:60)
	at scala.Option.getOrElse(Option.scala:121)
	at com.databricks.spark.redshift.RedshiftRelation.schema$lzycompute(RedshiftRelation.scala:60)
	at com.databricks.spark.redshift.RedshiftRelation.schema(RedshiftRelation.scala:59)
	at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:39)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:130)
	at com.sparkexamples.RedshiftTest$.main(RedshiftTest.scala:30)
	at com.sparkexamples.RedshiftTest.main(RedshiftTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.amazon.redshift.jdbc4.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.databricks.spark.redshift.Utils$.classForName(Utils.scala:42)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$getDriverClass$1.apply(RedshiftJDBCWrapper.scala:77)
```

**Comment by JoshRosen** [comment]
If you're using the postgres driver, change your JDBC URL to use the `postgresql://` subprotocol, .e.g.


```
val jdbcURL = "jdbc:postgresql://<host>:5439/<db>?user=<username>&password=<pass>"
```

This is discussed in the documentation for the `url` configuration option: https://github.com/databricks/spark-redshift#parameters

**Comment by samelamin** [comment]
Also I had the same issue before, you have to reference the redshift driver  then you wont need to use the postgres driver.

Amazon recommend using their driver so you might as well, keep it simple right :)

**Comment by robbyki** [comment]
Thank you. This seems to have worked after adding the 4.0 version of the redshift jdbc driver and continuing to use the `jdbc:redshift` protocol.

**Comment by JoshRosen** [comment]
Yep, that's the right approach: either use `jdbc:redshift` and the Amazon redshift driver, or use `jdbc:postgres` and the postgres driver. Going to resolve this issue.

**Comment by nimmicv** [comment]
does this also support java ?

**Comment by JoshRosen** [comment]
@nimmicv, how so? Although there aren't Java-language examples, `spark-redshift` should support usage from Java, as should most libraries which implement Spark's Data Sources API.

**Comment by nimmicv** [comment]
@JoshRosen . Thanks but I ma getting some errrors and trying to get over them 
http://stackoverflow.com/questions/38835371/load-data-from-redshift-using-spark-redshift-in-java

Any help appreciated

**Comment by JoshRosen** [comment]
@nimmicv, I can take a look. For the future, please file new issues rather than commenting on existing ones if you're asking about a new / distinct issue.

**Comment by nimmicv** [comment]
@JoshRosen .Thanks for your help.

**Comment by emptyr1** [comment]
Same issue here @JoshRosen :( Not sure what I'm doing wrong. I'm running [spark within docker with jupyter. ](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#core-stacks) -- the pyspark. I can access aws s3 and redshift fine without spark, so its not a permission issue. 
Using these commands: 

```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /home/jovyan/spark-redshift_2.10-3.0.0-preview1.jar,aws-java-sdk-1.11.534.jar,aws-java-sdk-s3-1.11.534.jar,aws-java-sdk-core-1.11.534.jar pyspark-shell'
redshift_url = "jdbc:redshift://10.200.1.205:5439/db?user=ben&password=" + urllib.parse.quote_plus("qweqwe123qweeqwe")
df = spark.read \
    .format("com.databricks.spark.redshift") \
    .option("url", redshift_url) \
    .option("query", "select * from users limit 10") \
    .option("tempdir", "/home/jovyan/redshift/") \
    .option("forward_spark_s3_credentials", "true") \
    .load()
```

I get error:
```
Py4JJavaError: An error occurred while calling o60.load.
: java.lang.ClassNotFoundException: Could not load an Amazon Redshift JDBC driver; see the README for instructions on downloading and configuring the official Amazon driver.
```

**Comment by ar-ms** [comment]
I was running into the same issue, here how I solved it:

First, I downloaded the jar from aws console (redshift  config page)
![image](https://user-images.githubusercontent.com/6579903/85035527-93662b00-b183-11ea-9b35-a672387e49ac.png)

Then submitted the jar using the spark options --jars.

``` sh
spark-submit --deploy-mode client \
    --jars /pathtojars/RedshiftJDBC42-no-awssdk-1.2.37.1061.jar \
    --packages org.apache.hadoop:hadoop-aws:2.7.7,org.apache.spark:spark-avro_2.11:2.4.4,com.databricks:spark-redshift_2.11:2.0.1 \
   file.py
```

I'm using spark version 2.4.5.

**Comment by pbanik1** [comment]
Hi, I'm new to Databricks.I'm trying to query a table that's in Redshift database using Databricks notebook.
df=(spark.read.format("redshift")
  .option("query","select * from <table_name>")
  .option("tempdir", "<dir_path>")
  .option("url", "jdbc:redshift://redshiftcluster-yjjpggtyai6n.c7clh6gyfzd5.us-east-1.redshift.amazonaws.com")
  .option("user", "user")
  .option("password", "password")
  #.option("forward_spark_s3_credentials", True)
  .load()
)
Getting the error: java.lang.ClassNotFoundException: 
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1672133348247317> in <module>
----> 1 df=(spark.read.format("redshift")
Can someone help please
