### ISSUE TITLE
SchemaParseException: Illegal character

### ISSUE THREAD

**Issue by samelamin** [databricks/spark-redshift#234]
Hey Guys

First of all great support on this project, really appreciate it

So my question is that I have a json that I am exploding and would like to save it to a redshift table.

I am using the explode function for the nested elements

I am reading in the json then using this line to get the row
```
    val paymentInfo = df.select("OrderContainer").withColumn("OrderContainer.PaymentInfo", 
explode($"OrderContainer.PaymentInfo.PaymentLines"))
```

But for some reason I am getting an illegal character 

below is the json

```
{"OrderContainer":{"PaymentInfo":{"OrderId":"foo","PaymentLines":[{"Type":"Cash","Value":18.8,"CardFee":0.0}],"DriverTipValue":0.0,"Total":18.8,"TotalComplementary":0.0,"PaidDate":"2016-07-06T10:58:51.7863535+00:00"}}}
```

**Comment by JoshRosen** [comment]
Can you please post a stacktrace to indicate which error you're seeing?

**Comment by samelamin** [comment]
Here is the stack trace

```
Exception in thread "main" org.apache.avro.SchemaParseException: Illegal character in: ordercontainer.paymentinfo
	at org.apache.avro.Schema.validateName(Schema.java:1083)
	at org.apache.avro.Schema.access$200(Schema.java:79)
	at org.apache.avro.Schema$Field.<init>(Schema.java:372)
	at org.apache.avro.SchemaBuilder$FieldBuilder.completeField(SchemaBuilder.java:2124)
	at org.apache.avro.SchemaBuilder$FieldBuilder.completeField(SchemaBuilder.java:2120)
	at org.apache.avro.SchemaBuilder$FieldBuilder.access$5200(SchemaBuilder.java:2034)
	at org.apache.avro.SchemaBuilder$FieldDefault.noDefault(SchemaBuilder.java:2146)
	at com.databricks.spark.avro.SchemaConverters$$anonfun$convertStructToAvro$1.apply(SchemaConverters.scala:110)
	at com.databricks.spark.avro.SchemaConverters$$anonfun$convertStructToAvro$1.apply(SchemaConverters.scala:105)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.databricks.spark.avro.SchemaConverters$.convertStructToAvro(SchemaConverters.scala:105)
	at com.databricks.spark.avro.AvroRelation.prepareJobForWrite(AvroRelation.scala:83)
	at org.apache.spark.sql.execution.datasources.BaseWriterContainer.driverSideSetup(WriterContainer.scala:103)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelation.scala:147)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation.run(InsertIntoHadoopFsRelation.scala:108)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:256)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at com.databricks.spark.redshift.RedshiftWriter.unloadData(RedshiftWriter.scala:278)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:346)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at Importer$.main(Importer.scala:46)
	at Importer.main(Importer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```


I am actually using this line to generate it 
```
    val paymentLines = df.withColumn("OrderContainer.PaymentInfo", explode($"OrderContainer.PaymentInfo.PaymentLines"))
```

**Comment by JoshRosen** [comment]
I think this is another case of #84: Avro field names can't contain the `.` character: https://avro.apache.org/docs/1.7.7/spec.html#Names. For now, I think you'll have to rename your field prior to saving to Redshift.

**Comment by samelamin** [comment]
ah ok i see, fair enough but can you help me out with the renaming syntax, because alias wont work :( 

Also doesnt that mean I will have to rename all columns that might have spaces in their name?

**Comment by samelamin** [comment]
Renamed columns using the .toDF("{newColumnName}") also FYI you can also use .alias 

closing now
