### ISSUE TITLE
Issues setting DirectOutputCommitter for RedshiftWriter

### ISSUE THREAD

**Issue by kyortsos** [databricks/spark-redshift#235]
I am trying to set a custom output committer for saving DataFrames to S3/Redshift in the same vein that I've overridden the FileOutputCommitter for `saveAsTextFile`, using Hadoop version 2.0.0 and Spark 1.6.1. I'm seeing a similar stack trace to [this issue](https://github.com/databricks/spark-redshift/pull/75)

```
2016-07-12 21:20:06,348 [JobScheduler         | ERROR] org.apache.spark.streaming.scheduler.JobScheduler - Error running job streaming job 1468358400000 ms.0
java.lang.ClassCastException: org.apache.hadoop.mapreduce.Job cannot be cast to org.apache.hadoop.mapred.JobContext
        at org.apache.hadoop.mapred.OutputCommitter.setupJob(OutputCommitter.java:146)
        at org.apache.spark.sql.execution.datasources.BaseWriterContainer.driverSideSetup(WriterContainer.scala:108)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelation.scala:147)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation.run(InsertIntoHadoopFsRelation.scala:108)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:256)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
        at com.databricks.spark.redshift.RedshiftWriter.unloadData(RedshiftWriter.scala:323)
        at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:388)
        at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
```

Setting the config as such: `sc.hadoopConfiguration.set("spark.sql.sources.outputCommitterClass", classOf[DirectOutputCommitter].getCanonicalName)` where `DirectOutputCommitter` is taken from the same PR. Any help here?

**Comment by JoshRosen** [comment]
My hunch is that an incompatible version of `avro-mapred` is winding up on your classpath (which is why the trick in https://github.com/databricks/spark-redshift/pull/75/files#diff-3f507b079afcdf2a7e0d8af6a216a80eR104 was necessary). I'd check your classpath to see whether the `hadoop1`-classified version of that artifact is being pulled in.

**Comment by kyortsos** [comment]
Thanks for the hint. I'm not seeing anything weird with my classpath, and am now seeing this exception: 
```java.lang.RuntimeException: java.lang.RuntimeException: class com.databricks.spark.redshift.DirectOutputCommitter not org.apache.hadoop.mapred.OutputCommitter
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1752)
	at org.apache.hadoop.mapred.JobConf.getOutputCommitter(JobConf.java:722)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:1041)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:952)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:951)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1457)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1436)
	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1436)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1436)
```
Is this the same issue?

**Comment by JoshRosen** [comment]
The problem is that Hadoop has two different `OutputCommitter` APIs, one in `mapred` and another in `mapreduce`, which is why the current `spark-redshift` test source tree contains two separate DirectOutputCommitter implementations:

- https://github.com/databricks/spark-redshift/blob/master/src/test/scala/com/databricks/spark/redshift/DirectMapredOutputCommitter.scala
- https://github.com/databricks/spark-redshift/blob/master/src/test/scala/com/databricks/spark/redshift/DirectMapreduceOutputCommitter.scala

Note that there are a few corner-cases related to DirectOutputCommitter which can cause complications in real workloads if you're not careful, so I'd be cautious about using this. If you're seeing a lot of expensive copying in S3, I'd first consider switching to `s3a://` since I think that will take advantage of S3's built-in fast server-side copy capabilities.

**Comment by kyortsos** [comment]
Interesting. I've tried switching over to `s3a://` (running Spark on EC2) but unfortunately there is a breaking change in newer versions of the AWS API [Jira](https://issues.apache.org/jira/browse/HADOOP-12420) that requires a much older version of the AWS SDK library to get s3a working, which is too old for the Kinesis stuff I'm doing. Considering your aforementioned "complications", I may just hold off on this until the Hadoop fix version is stable. Thanks for your help.
