### ISSUE TITLE
spark-redshift in R through sql?

### ISSUE THREAD

**Issue by omiddjoudi** [databricks/spark-redshift#237]
Hi,
Is it possible to use spark-redshift in R through sql?

In Spark-sql the following command works fine:

```sql
    create table flights2
    USING com.databricks.spark.redshift
    OPTIONS (
    dbtable 'schema1.flights2',
    tempdir 's3n://.../tmp',
    url 'jdbc:redshift:...'
    )
    AS SELECT * FROM flights;

```
Where flights is the name of the table loaded previously in Hive.

But in R the following command fails after some time if the data size is big, even by increasing the size of executory memory and driver memory.

```r
    sql (hiveContext, 
         "CREATE TABLE flights2
         USING com.databricks.spark.redshift
         OPTIONS 
         (
         dbtable 'schema1.flights2',
         tempdir 's3n://.../tmp',
         url 'jdbc:redshift:...'
         )
         AS SELECT * FROM tempTable
         "
    );

```
tempTable has been created from a spark dataframe using :

```r
    registerTempTable(df, "tempTable")
    cacheTable(hiveContext, "tempTable")

```
 
The error is :

```
16/07/13 16:12:29 WARN TransportChannelHandler: Exception in connection from ip-10-247-24-60.bigdata.cloud.danet/10.247.24.60:35560
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:313)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
```

Any advice?

**Comment by JoshRosen** [comment]
Yes, this library should support SparkR. I don't believe that the error message that you're seeing is specific to the combination of `spark-redshift` + R, so I don't believe that this ticket is actionable in its current form. You'll need to provide more specific error information and logs (e.g. driver logs, executor logs, a description of whether a task failed or the whole job, etc.) before this is debuggable.
