### ISSUE TITLE
ClassNotFoundException Errors

### ISSUE THREAD

**Issue by yicunqian** [databricks/spark-redshift#245]
So I just recently managed to set up spark 1.6.1 on a EC2 instance and was about to test the functionality of spark-redshift module. I am using PySpark for coding and when I tried to implement reading tables from redshfit to s3 I got an error.
Below is an error message I got from the command line. 

```
Py4JJavaError: An error occurred while calling o35.load.
: java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/S3ObjectInputStream
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:49)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:158)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.s3.model.S3ObjectInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

I saw the notes in readme but I haven't figured out a solution on my own. If anyone can show a specific way of adding dependencies on the AWS SDKs I'm pleased to know.

**Comment by JoshRosen** [comment]
Please see the dependency management instructions in the Spark documentation: https://spark.apache.org/docs/1.6.1/submitting-applications.html#advanced-dependency-management

You should be able to use `--packages` to specify Maven coordinates for the AWS Java SDK, e.g.

```
--packages com.amazonaws:aws-java-sdk-s3:1.11.21,<your-spark-redshift-maven-coordinate>
```


(Note this is a comma-delimited list).

Alternatively, download the AWS SDK JARs and use `--jars` to add them to Spark's classpath.
