### ISSUE TITLE
`aws_iam_role` not being used

### ISSUE THREAD

**Issue by Gauravshah** [databricks/spark-redshift#252]
have set the following:
```
    df.write
      .format("com.databricks.spark.redshift")
      .option("url", jdbcConnectionString)
      .option("aws_iam_role",IAMRole)
      .option("tempdir", s"s3://$tmpBucketName/test_gaurav/query/$tableName")
      .option("dbtable", tableName)
      .mode(mode)
      .save()
```

But I get exception:
```
Failed due to error: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
```
Trace:
```
java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively).
	at com.databricks.spark.redshift.S3Credentials.initialize(S3Credentials.java:67)
	at com.databricks.spark.redshift.AWSCredentialsUtils$.com$databricks$spark$redshift$AWSCredentialsUtils$$loadFromURI(AWSCredentialsUtils.scala:60)
	at com.databricks.spark.redshift.AWSCredentialsUtils$$anonfun$load$1.apply(AWSCredentialsUtils.scala:48)
	at com.databricks.spark.redshift.AWSCredentialsUtils$$anonfun$load$1.apply(AWSCredentialsUtils.scala:48)
	at scala.Option.getOrElse(Option.scala:121)
	at com.databricks.spark.redshift.AWSCredentialsUtils$.load(AWSCredentialsUtils.scala:48)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:338)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at com.poshmark.spark.helpers.Redshift$.writeDF(Redshift.scala:74)
	at com.poshmark.spark.streaming.RedshiftBasin$$anonfun$kinesisBasinFunction$1.apply(RedshiftBasin.scala:43)
	at com.poshmark.spark.streaming.RedshiftBasin$$anonfun$kinesisBasinFunction$1.apply(RedshiftBasin.scala:15)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Verified that EC2 instance roles has access:
```
irb(main):004:0> require 'aws-sdk'
=> true
irb(main):005:0> 
irb(main):006:0* s3 = Aws::S3::Resource.new(region:'us-west-2')
=> #<Aws::S3::Resource>
irb(main):007:0> obj = s3.bucket('$tmpBucket').object("test")
=> #<Aws::S3::Object bucket_name="$tmpBucket", key="test">
irb(main):008:0> obj.put(body: "foobar")
=> #<struct Aws::S3::Types::PutObjectOutput expiration=nil, etag="\"f970e2767d0cfe75876ea857f92e319b\"", server_side_encryption=nil, version_id=nil, sse_customer_algorithm=nil, sse_customer_key_md5=nil, ssekms_key_id=nil, request_charged=nil>
irb(main):009:0> exit
```

Looking from code:
/Users/gaurav/.ivy2/cache/com.databricks/spark-redshift_2.11/srcs/spark-redshift_2.11-2.0.0-sources.jar!/com/databricks/spark/redshift/RedshiftWriter.scala:
```
def saveToRedshift(
...
    val creds: AWSCredentials =
      AWSCredentialsUtils.load(params, sqlContext.sparkContext.hadoopConfiguration)
...
```

this tries only to load from temporary creds or url ( not from the role)
```
  def load(params: MergedParameters, hadoopConfiguration: Configuration): AWSCredentials = {
    params.temporaryAWSCredentials.getOrElse(loadFromURI(params.rootTempDir, hadoopConfiguration))
  }
```

**Comment by JoshRosen** [comment]
To clarify the docs slightly, the `aws_iam_role` parameter is used for controlling the IAM role that Redshift itself will assume when performing reads / writes to S3. This is why [`aws_iam_role` is read in `getCredentialsString()`](https://github.com/databricks/spark-redshift/blob/2cc51b691d4c85ff3ea801a8528942a8111cb9c2/src/main/scala/com/databricks/spark/redshift/AWSCredentialsUtils.scala#L32) but not elsewhere. `spark-redshift` also needs credentials for Spark itself to access S3 so that it can perform listing operations, write manifest files, etc.

I'm guessing that you also want to use IAM to authenticate Spark with S3. By default this is _supposed_ to work out of the box if you're on EC2 and are using instance roles since the AWS SDKs should automatically use an instance role provider based set of credentials, but I guess the problem here is that `spark-redshift` is not handling those properly in `AWSCredentialsUtils.load()`.

As an immediate workaround, you can follow the instructions for using STS credentials and use those to appease the credential-handling checks, but in the longer term we need to refactor the internal handling of credentials to automatically use InstanceProfileCredentialsProvider when appropriate.

**Comment by Gauravshah** [comment]
so we need to pass  `aws_iam_role` `temporary_aws_session_token` `temporary_aws_key` & `temporary_aws_secret` ?

**Comment by JoshRosen** [comment]
Yeah, I think that should be sufficient, but in an ideal world it wouldn't be necessary.

**Comment by Gauravshah** [comment]
thanks for the clarification

**Comment by Gauravshah** [comment]
@JoshRosen can you help me a little more on this one.
Getting following when using temp_creds:

```
com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: D4FAF10CDCDC9A7E), S3 Extended Request ID: wkCl2VD+Tn5W0uee/+91BqGvrUHgQONInnbatgOIOVqP6S5IOskZ9YujCKo7Yr1y3bfT6bBeBS0=
```

Trace:
```
com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: D4FAF10CDCDC9A7E), S3 Extended Request ID: wkCl2VD+Tn5W0uee/+91BqGvrUHgQONInnbatgOIOVqP6S5IOskZ9YujCKo7Yr1y3bfT6bBeBS0=
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1015)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:991)
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy29.retrieveMetadata(Unknown Source)
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.getFileStatus(S3NativeFileSystem.java:780)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1428)
	at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.exists(EmrFileSystem.java:313)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:85)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:60)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:136)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:133)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:86)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:487)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:194)
	at com.databricks.spark.redshift.RedshiftWriter.unloadData(RedshiftWriter.scala:278)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:346)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at com.poshmark.spark.helpers.Redshift$.writeDF(Redshift.scala:82)
	at com.poshmark.spark.streaming.RedshiftBasin$$anonfun$kinesisBasinFunction$1.apply(RedshiftBasin.scala:43)
	at com.poshmark.spark.streaming.RedshiftBasin$$anonfun$kinesisBasinFunction$1.apply(RedshiftBasin.scala:15)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I have my emr in us-west-1 and s3 & redshift in us-west2. Looks like region issue but unable to figure the reason since we are not using any url.

code:
```
    val provider = new DefaultAWSCredentialsProviderChain()
    val credentials: AWSSessionCredentials = provider.getCredentials.asInstanceOf[AWSSessionCredentials]

    df.write
      .format("com.databricks.spark.redshift")
      .option("url", jdbcConnectionString)
      .option("aws_iam_role",IAMRole)
      .option("temporary_aws_access_key_id",credentials.getAWSAccessKeyId)
      .option("temporary_aws_secret_access_key",credentials.getAWSSecretKey)
      .option("temporary_aws_session_token",credentials.getSessionToken)
      .option("tempdir", s"s3://$tmpBucketName/test_gaurav/query/$tableName")
      .option("dbtable", tableName)
      .mode(mode)
      .save()

```

**Comment by JoshRosen** [comment]
Note that `spark-redshift` does not currently support cross-region transfers where the Spark cluster and Redshift cluster reside in different AWS regions; see #87.

**Comment by Gauravshah** [comment]
if redshift had failed to load I would understand, but I could not understand why writing to S3 it self would fail. Thanks @JoshRosen

**Comment by JoshRosen** [comment]
You may need to configure your S3 client endpoints based on your region. Are you able to write to the S3 bucket using Spark without using `spark-redshift`? We should figure out whether this connectivity issue is somehow specific to the `spark-redshift` library and its use of S3.

**Comment by Gauravshah** [comment]
yup I am able to write to same bucket if I use parquet.write. I then tried
using `region.bucket_name` (I know sounds weird) but that worked writing to
s3, but redshift was unable to understand the url.
