### ISSUE TITLE
Amazon Invalid operation: S3ServiceException:The specified bucket does not exist

### ISSUE THREAD

**Issue by nimmicv** [databricks/spark-redshift#257]
java.sql.SQLException: [Amazon](500310) Invalid operation: S3ServiceException:The specified bucket does not exist,Status 404,Error NoSuchBucket,Rid AA6E01BF9BCED7ED,ExtRid 7TQKPoWU5lMdJ9av3E0Ehzdgg+e0yRrNYaB5Q+WCef0JPm134XHeiSNk1mx4cdzp,CanRetry 1
Details: 
 -----------------------------------------------
  error:  S3ServiceException:The specified bucket does not exist,Status 404,Error NoSuchBucket,Rid AA6E01BF9BCED7ED,ExtRid 7TQKPoWU5lMdJ9av3E0Ehzdgg+e0yRrNYaB5Q+WCef0JPm134XHeiSNk1mx4cdzp,CanRetry 1
  code:      8001
  context:   Listing bucket=redshift-spark.s3.amazonaws.com prefix=s3Redshift/3a312209-7d6d-4d6b-bbd4-c1a70b2e136b/
  query:     0
  location:  s3_unloader.cpp:200
  process:   padbmaster [pid=4952]
  -----------------------------------------------;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:804)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:642)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1062)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(PGMessagingContext.java:1030)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario2ForPrepareExecution(PGClient.java:2417)
	at com.amazon.redshift.client.PGClient.handleErrorsPrepareExecute(PGClient.java:2358)
	at com.amazon.redshift.client.PGClient.executePreparedStatement(PGClient.java:1358)
	at com.amazon.redshift.dataengine.PGQueryExecutor.executePreparedStatement(PGQueryExecutor.java:370)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(PGQueryExecutor.java:245)
	at com.amazon.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:101)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:101)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$2.apply(RedshiftJDBCWrapper.scala:119)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

I have the bucket created in S3

**Comment by JoshRosen** [comment]
Per your StackOverflow question, it looks like this was resolved by switching to a newer version of the AWS Java SDK: https://stackoverflow.com/questions/38840119/s3-bucket-missing-redshift-spark

This issue may also be fixed by #254 in 1.1.0 / 2.0.1, so please try those versions in case you hit this problem again.

I'm going to resolve this issue now, but please re-open if this issue is still present in the latest releases. Thanks!
