### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory

### ISSUE THREAD

**Issue by cfrancocapo** [databricks/spark-redshift#260]
Hi,
I am getting an error due to dependency resolution issue I guess.

[INFO] +- com.databricks:spark-redshift_2.10:jar:1.1.0:compile
[INFO] |  \- com.databricks:spark-avro_2.10:jar:2.0.1:compile
[INFO] +- com.amazonaws:aws-java-sdk-core:jar:1.11.23:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.6:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.23:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kms:jar:1.11.23:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile

As you can see the httpclient version is in the classpath. Any idea?

`Caused by: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:91)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:51)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:39)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:282)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:164)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:520)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:500)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:482)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:454)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:436)
	at com.databricks.spark.redshift.DefaultSource$$anonfun$$init$$1.apply(DefaultSource.scala:39)
	at com.databricks.spark.redshift.DefaultSource$$anonfun$$init$$1.apply(DefaultSource.scala:39)`

**Comment by cfrancocapo** [comment]
Hi,
I think I found the issue. The ClassLoader is loading the class from an incorrect jar.

jar:file:/spark/lib/spark-assembly-1.6.1-hadoop2.4.0.jar!/org/apache/http/conn/ssl/SSLConnectionSocketFactory.class

Instead of org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar!/org/apache/http/conn/ssl/SSLConnectionSocketFactory.class

**Comment by cfrancocapo** [comment]
I fixed with maven-shade-plugin
<relocation>
 <pattern>org.apache.http</pattern>
 <shadedPattern>shaded.org.apache.http</shadedPattern>
</relocation>

**Comment by LalithAravind** [comment]
Hi JoshRosen  & cfrancocapo ,

I am facing the same problem mentioned above,
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56) **** 

I have updated the httpClient jar in my buildpath to httpclient-4.5.4, and its worked in my local environment. 

but when I am deployed it into WSO2EI server, again its referring httpclient_4.3.2.wso2v1 from wso2home/repository/components/plugins folder. 
unable to resolve the issue. 

Is there any other way to modify the jar its referring at runtime
