### ISSUE TITLE
NumberFormatException when reading NaN value

### ISSUE THREAD

**Issue by wwinnicki** [databricks/spark-redshift#261]
Hello,

I noticed problems reading Redshift data having NaN value.
As i understand NaN is proper Redshift value for some numerical types. But it fails when converting in spark-redshift code.

I made ugly workaround just to load my data - I added this to Conversion.scala:
Line 85,86,87: **if("nan".equalsIgnoreCase(data)) null else** data.toDouble

Probably it should be corrected in some better way.

The original error was:
```
16/08/30 04:02:20 WARN scheduler.TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2, euw1z1pl004): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:272)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "nan"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:232)
	at scala.collection.immutable.StringOps.toDouble(StringOps.scala:31)
	at com.databricks.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$4.apply(Conversions.scala:87)
	at com.databricks.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$4.apply(Conversions.scala:87)
	at com.databricks.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:105)
	at com.databricks.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:101)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:263)
	... 8 more
```

Regards, Wojtek

**Comment by JoshRosen** [comment]
Good catch!

To fix this, I think we should special-case handling of `NaN` in https://github.com/databricks/spark-redshift/blob/69aa802b9091ec24fc187e45b38906248ba8f010/src/main/scala/com/databricks/spark/redshift/Conversions.scala#L89 in order to return `Float.NaN`. I think that defaulting to treating `NaN` values as `null` is an undesirable behavior because it's lossy (Spark provides built-in UDFs for converting `NaN` to `null`, so there's not a huge user-friendliness gain from this either).

If Redshift had returned `NaN` instead of `nan` then we could use `Float.parseFloat` for this:

```scala
scala> java.lang.Float.parseFloat("nan")
java.lang.NumberFormatException: For input string: "nan"
  at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
  at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
  at java.lang.Float.parseFloat(Float.java:451)
  ... 28 elided

scala> java.lang.Float.parseFloat("NaN")
res9: Float = NaN
```

We should add a unit test in [`ConversionsSuite`](https://github.com/databricks/spark-redshift/blob/69aa802b9091ec24fc187e45b38906248ba8f010/src/test/scala/com/databricks/spark/redshift/ConversionsSuite.scala#L30).

We should also fix this for positive and negative infinity.

We should also add a roundtrip test to `RedshiftIntegrationSuite` in order to make sure that we can also write these special floating-point values. I'd model my test after https://github.com/databricks/spark-redshift/blob/69aa802b9091ec24fc187e45b38906248ba8f010/src/it/scala/com/databricks/spark/redshift/RedshiftIntegrationSuite.scala#L335

If you have time, feel free to submit a PR for this. Otherwise I can try to put one together later.

**Comment by JoshRosen** [comment]
It looks like Redshift doesn't allow you to copy NaN values, so the roundtrip test won't work quite as expected: https://forums.aws.amazon.com/thread.jspa?threadID=236367

For now, users can choose to work around this by explicitly choosing to treat NaN as null when writing.
