### ISSUE TITLE
Exception writing to redshift using the python API

### ISSUE THREAD

**Issue by mihirkelkar** [databricks/spark-redshift#270]
Im trying to write a fairly large dataframe to a redshift table and have been getting the following error for a while now : 

```
py4j.protocol.Py4JJavaError: An error occurred while calling o448.save.
: java.lang.AbstractMethodError: com.databricks.spark.redshift.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/DataFrame;)Lorg/apache/spark/sql/sources/BaseRelation;
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
```

My code that performs the save operation look like this : 

```
dataframe.write\
        .format("com.databricks.spark.redshift")\
        .option("url", self.databricks_url)\
        .option("dbtable", table_name)\
        .option("tempdir", "s3n://tradesy-redshift")\
        .option("jdbcdriver", self.jdbcdriver)\
        .mode(write_mode)\
        .save()
```

where self.databricks_url is my redshift endpoint in the correct specified format and write_mode is 'Append'

Im passing the following packages to my spark-submit command

```
 --packages com.databricks:spark-redshift_2.11:2.0.1,com.amazonaws:aws-java-sdk-core:1.10.11,com.amazonaws:aws-java-sdk-s3:1.10.11,com.amazonaws:aws-java-sdk-pom:1.10.34,org.apache.hadoop:hadoop-aws:2.6.0  --jars RedshiftJDBC41-1.1.17.1017.jar
```

My spark version is 1.6.2 with hadoop 2.6

I have been using the same jdbc driver to read some pre-existing data from the same redshift table and that has been working find.

**Comment by JoshRosen** [comment]
`spark-redshift` 2.x is only compatible with Spark 2.x; for Spark 1.6 you should be using a 1.x version of `spark-redshift`, such as https://github.com/databricks/spark-redshift/releases/tag/v1.1.0
