### ISSUE TITLE
Opaque exception thrown on dataframe save (Python)

### ISSUE THREAD

**Issue by ctweney** [databricks/spark-redshift#271]
I'm trying to upgrade an existing Spark 1.5/Spark-Redshift 0.5.2 Python app to the current latest of each (Spark 2.0.0/Spark-Redshift 1.1.0). 

I'm using the official binary distribution of spark-2.0.0-bin-hadoop2.7. Java 1.8.0_60 on OSX. Python is 3.5.1.

Spark command options:

```--packages com.databricks:spark-redshift_2.11:1.1.0,com.amazonaws:aws-java-sdk-core:1.11.36,com.amazonaws:aws-java-sdk-s3:1.11.36 --conf spark.hadoop.fs.s3n.impl=org.apache.hadoop.fs.s3native.NativeS3FileSystem --conf spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3.S3FileSystem```

My save code looks like this (temp_table is already registered as a temporary table via df.registerTempTable):

```        
        sql = self.spark.sql("SELECT * FROM {:s}".format(temp_table)) \
                        .write.format("com.databricks.spark.redshift") \
                        .option("url", self.redshift_jdbc_url) \
                        .option("tempdir", self.redshift_temp_dir) \
                        .option("dbtable", redshift_table) \
                        .option("extracopyoptions", "ACCEPTINVCHARS") \
                        .option("diststyle", diststyle)
        if distkey is not None:
            sql = sql.option("distkey", distkey)
        if sortkeyspec is not None:
            sql = sql.option("sortkeyspec", sortkeyspec)

        sql.mode(save_mode).save()
```

When it gets to the save() call I get a very uninformative exception with not much detail: 

```
  File "/Users/chris/dev/rails4-rescuetime/p3rt/rt/analytics/spark.py", line 112, in save_table_to_redshift
    sql.mode(save_mode).save()
  File "/Users/chris/spark-2.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 530, in save
  File "/Users/chris/spark-2.0.0-bin-hadoop2.7/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 933, in __call__
  File "/Users/chris/spark-2.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/Users/chris/spark-2.0.0-bin-hadoop2.7/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o70.save.
: java.lang.AbstractMethodError: com.databricks.spark.redshift.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/sources/BaseRelation;
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:128)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:211)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment]
If you're using Spark 2.x then you should use a 2.x version of `spark-redshift`; try using version 2.0.1 instead.

It's unfortunate that GitHub's "versions" page doesn't sort according to semantic versioning instead of chronologically newest version; I can see how the current scheme is confusing. I'll try to update the release notes and README to be clearer about this. I suppose that the 2.x code could also check `SPARK_VERSION` and throw an exception in case it detects that it is being used with Spark 1.x.

**Comment by ctweney** [comment]
Thanks - using spark-redshift 2.0.1 solved my woes. 

It'd be awesome if the readme included current specifics on Python setup. I had to google around to find a --packages argument that then turned out to be outdated.
