### ISSUE TITLE
Error when writing table to Redshift

### ISSUE THREAD

**Issue by jlshin** [databricks/spark-redshift#280]
version info: emr-5.0, spark 2.0, hadoop  2.7.2 

I am using the latest spark-redshift (`com.databricks:spark-redshift_2.10:1.1.0`) package. I set up IAM roles and have successfully been able to read a table from Redshift with this package's API, but when I try to write a table to Redshift an error occurs.

Here's what I run:

```
df.write \
  .format("com.databricks.spark.redshift") \
  .option("url", jdbc_url) \
  .option("dbtable", "new_table") \
  .option("tempdir", "s3a://...") \
  .option("aws_iam_role",arn_) \
  .mode("overwrite") \
  .save()        
```

Here's the Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/lib/spark/python/pyspark/sql/readwriter.py", line 530, in save
    self._jwrite.save()
  File "/usr/lib/spark/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 933, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o425.save.
: java.lang.AbstractMethodError: com.databricks.spark.redshift.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/sources/BaseRelation;
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:429)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:128)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:211)
	at java.lang.Thread.run(Thread.java:745)

```

I have the IAM roles set up so that my EMR cluster has full access to redshift (AmazonRedshiftFullAccess) and S3 (AmazonS3FullAccess). Redshift is set up to also have full access to S3, EC2 and EMR.

Thanks in advance.

**Comment by JoshRosen** [comment]
If you're using Spark 2.x then you need to use `spark-redshift` 2.x. Try using 

```
com.databricks:spark-redshift_2.10:2.0.1
```

instead.

**Comment by JoshRosen** [comment]
Since this is the third time that GitHub's default ordering of release versions has led to confusion, I've added the following text at the top of the release notes:

> ⚠️  **Important**: If you are using Spark 2.x, then use [v2.0.1](https://github.com/databricks/spark-redshift/releases/tag/v2.0.1) instead. 1.x releases of this library are only compatible with Spark 1.x.
