### ISSUE TITLE
Save to redshift completes, but the job never ends

### ISSUE THREAD

**Issue by lminerPlaid** [databricks/spark-redshift#290]
I'm running a job in spark that reads in a dataframe from parquet, and splits it into three separate dataframes and writes these dataframes to tables in redshift. Although, spark successfully writes to redshift, all the tables and rows are there, the job itself never finishes. The last message logged is:

`16/10/25 20:57:57 INFO ContextCleaner: Cleaned accumulator 0`

The code for writing to redshift in pyspark is as follows:

```python
(table
     .write
     .format("com.databricks.spark.redshift")
     .option("url", "jdbc:redshift://foo.amazonaws.com:5439/foo?user=foo&password=foo")
     .option("dbtable", table_name)
     .option("tempdir", "s3a://foo/tmp/redshift")
     .option("extracopyoptions", "TRUNCATECOLUMNS")
     .mode("overwrite")
     .save())
```

I'm running spark 2.0.1-hadoop 2.7, spark-redshift_2.11-2.0.1.jar, RedshiftJDBC41-1.1.17.1017.jar

**Comment by JoshRosen** [comment]
If you run `jstack` on the driver then what do you see? My hunch is that the write of Avro files to S3 has succeeded but that Redshift is being slow in actually processing those written files, so I'd expect to see your driver hanging in a JDBC call.

I wish there was a mechanism to perform better progress reporting here, but it's tricky because this takes place outside the context of a Spark job.

The experimental CSV write support, added in #288, may help to speed this up; keep your eyes peeled for a 3.0.0-preview1 release that includes that patch.

**Comment by lminerPlaid** [comment]
It does appear like all the rows are in the table though. Doesn't that mean that redshift has processed everything or is that not necessarily the case?

Here's a snippet of a jstack dump

```
"Attach Listener" daemon prio=10 tid=0x00007f6ca4001000 nid=0xc03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"SparkUI-3714" daemon prio=10 tid=0x00007f6cc8033000 nid=0x44d waiting on condition [0x00007f6cb7efd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c2abe428> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at org.spark_project.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:389)
	at org.spark_project.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:531)
	at org.spark_project.jetty.util.thread.QueuedThreadPool.access$700(QueuedThreadPool.java:47)
	at org.spark_project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
```

**Comment by JoshRosen** [comment]
Not necessarily, given that you're using `overwrite` mode: this library uses transactions in a way that should ensure that the overwrite operation appears atomic to readers, so it's possible that you'd see the old contents of the table after the Spark to S3 write has completed but before the S3 to Redshift ingest has finished.

The `jstack` snipped that you shared isn't quite the part that I was looking for, since those threads aren't the ones that represent the main control flow of your application. Could you grep through the output to see if any threads have `redshift` or `jdbc` in their stacks?

**Comment by lminerPlaid** [comment]
I did a grep for redshift and jdbc and nothing came up. I did run jstack with the -l flag.

This is actually the very first time I've run this job, so there aren't any older versions of the same tables...

One thing I forgot to mention is that I did see this warning occasionally earlier in the job.

```
16/10/25 20:35:22 WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 76BB66ADA28129D0, AWS Error Code: AccessDenied, AWS Error Message: Access Denied, S3 Extended Request ID: ULZBTfCaAN5ppjptDc3hlY2qneVVSgwMhBGhsF5QizOB0GPBaHAc7mXnIuTo9aLkyRduofRQiZ8=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3480)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketLifecycleConfiguration(AmazonS3Client.java:1872)
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:127)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:343)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:442)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment]
That's a harmless warning and isn't the cause of your problem.

Given all of this, what's preventing the job from ending? Does control not return back to your Python driver program? Does your Python driver program never exit (i.e. by "job" are you referring to the lifecycle of an entire script passed to `spark-submit`)? What does the Spark web UI show?

**Comment by lminerPlaid** [comment]
The python driver program never exits. Wasn't sure how to refer to that, I suppose job wasn't the best choice :) The last line in the script is simply the command to write the dataframe to redshift that I included at the head of this thread. I do run scripts via `spark-submit` multiple times per day and I've never had this problem before.

According to the UI, all jobs have completed successfully and there are no pending or failed jobs.

**Comment by lminerPlaid** [comment]
So I added I stopped the `SparkSession` explicitly with a call to `spark.stop()` at the end of my script and this seemed to solve the problem.

**Comment by JoshRosen** [comment]
Aha, that makes sense: in case there are any non-daemon threads inside of Spark then you'll need to add that to ensure that Spark properly cleans everything up. Glad you were able to figure it out!
