### ISSUE TITLE
java.io.IOException : S3 Bad request 

### ISSUE THREAD

**Issue by aneja-rahul** [databricks/spark-redshift#298]
I am using spark-redshift  to read and write data on redshift. It was runnnig fine when our redshift cluster and bucket was in singapore region but after moving to mumbai region (which only supports V4 S3 version) i have started facing below exception 

java.io.IOException: s3n://BUCKETNAME/TEMPDIR  : 400 : Bad Request
at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.processException(Jets3tNativeFileSystemStore.java:453)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.processException(Jets3tNativeFileSystemStore.java:427)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.handleException(Jets3tNativeFileSystemStore.java:411)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

I am using spark 1.4.1 and spark-redshift 0.6.0 version
Couple of things I have already tried but no luck
1. adding s3 endpoint to hadoop configuration
2. setting aws sdk property ENABLE_S3_SIGV4_SYSTEM_PROPERTY to true
3. specifying region (ap-south-1) as a parameter while writing

**Comment by JoshRosen** [comment]
Head's up: those are really old versions of both this library and Spark, so I'm not going to be able to provide support for either of them here.

**Comment by aneja-rahul** [comment]
Hi Josh ,

I tried with spark 2.1.0 version and spark redshift 3.0.0-preview1 version . 

Still getting the below exception 

org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: S3 HEAD request failed for '/temp%asdasdadaca' - ResponseCode=400, ResponseMessage=Bad Request
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.handleServiceException(Jets3tNativeFileSystemStore.java:245)
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at org.apache.hadoop.fs.s3native.$Proxy26.retrieveMetadata(Unknown Source)
	at org.apache.hadoop.fs.s3native.NativeS3FileSystem.getFileStatus(NativeS3FileSystem.java:414)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1397)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:77)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)

**Comment by aneja-rahul** [comment]
@JoshRosen 

Can you please check this issue?

Thanks,
Rahul Aneja

**Comment by NeilJonkers** [comment]
Hi Rahul, 

Please test the following, add the following settings to your code.
Do not use S3n use S3a instead. S3n does not work well with SigV4 regions I found.

== start script ==
System.setProperty("com.amazonaws.services.s3.enableV4", "true")
sc.hadoopConfiguration.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
sc.hadoopConfiguration.set("com.amazonaws.services.s3.enableV4", "true")
sc.hadoopConfiguration.set("fs.s3a.endpoint", "s3.ap-south-1.amazonaws.com")
sc.hadoopConfiguration.set("fs.s3a.access.key", "XXXXXXXXXX") // Not needed if your instance use EC 2 instance roles
sc.hadoopConfiguration.set("fs.s3a.secret.key", "XXXXXXXXXX") // Not needed if your instance use EC 2 instance roles

val data = sc.textFile("s3a://BUCKET-IN-ap-south-1/filename")
data.count

== end script ==

**Comment by amitvalse** [comment]
Our redshift cluster and s3 bucket are in Mumbai region and i was able to fix this Bad request error on spark local mode but was not able to solve it in clustered environment.

I have posted the problem [here](http://stackoverflow.com/questions/41635704/amazon-s3a-returns-400-bad-request-with-spark-redshift-library)
