### ISSUE TITLE
Error while using spark-redshift jar

### ISSUE THREAD

**Issue by ghost** [databricks/spark-redshift#315]
Hi,

 Getting the below error while using the jar to integrate redshift with spark locally.

```
Exception in thread "main" java.lang.AbstractMethodError: com.databricks.spark.redshift.RedshiftFileFormat.prepareRead(Lorg/apache/spark/sql/SparkSession;Lscala/collection/immutable/Map;Lscala/collection/Seq;)Lscala/collection/immutable/Map;

at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:160)
	at com.databricks.spark.redshift.RedshiftRelation.buildScan(RedshiftRelation.scala:168)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:141)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$3.apply(DataSourceStrategy.scala:141)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:184)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:183)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:257)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:179)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:137)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:59)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:60)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.planLater(QueryPlanner.scala:55)
	at org.apache.spark.sql.execution.SparkStrategies$SpecialLimits$.apply(SparkStrategies.scala:54)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:59)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:59)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:60)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:75)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:82)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:82)
	at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2462)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:1861)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2078)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:240)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:533)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:493)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:502)
	at simpleSample.RedshiftToSpark$.main(RedshiftToSpark.scala:53)
	at simpleSample.RedshiftToSpark.main(RedshiftToSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

I find that prepareRead method is not in the RedshiftFileFormat.

Thanks & Regards,
Ravi

**Comment by JoshRosen** [comment]
Actually, looking a little more closely since this problem relates to `prepareRead` I don't think it's a 2.1.x issue since that method had been completely removed from Spark by that point (see https://github.com/apache/spark/pull/13698). According to https://issues.apache.org/jira/browse/SPARK-15983 that change went into 2.0. 

Thus: are you using a newer version of `spark-redshift` with Spark 1.x? You'll need to use a 1.x version of this library with Spark 1.x; newer versions won't work with Spark 1.x.

**Comment by lminer** [comment]
I'm getting the same exception with a different stack trace and only when I switch from spark 2.0.1 to spark 2.1.0/hadoop 2.7/mesos:

```
48f7-81e8-02403dbc2b57-S107): java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schwartzmx** [comment]
I'm getting this error as well, with spark 2.1.0,  I've also tried using the 3.0.0-preview1 of this library, previously was using 2.0.0.
```
java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lminer** [comment]
@JoshRosen Any plans to make a new release soon? Seems like it's needed to use this with 2.1.0.

**Comment by elyast** [comment]
@JoshRosen hit the same issue after upgrading from Spark 2.0.2 to Spark 2.1.0 our pipeline started throwing exceptions with the same cause

```
Caused by: java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
```

We are using spark-redsfhit 2.0.1 with https://s3.amazonaws.com/redshift-downloads/drivers/RedshiftJDBC41-1.1.17.1017.jar

**Comment by carlos-eduardo-gb** [comment]
@elyast hit the same issue using spark 2.1.0. 

[I make this question in Stackoverflow](http://stackoverflow.com/questions/41764899/spark-redshift-error-save-using-spark-2-1-0)

Using the version 2.0.2 of Spark you have the same issue? I'm not able to make the spark-redshift work in 2.0.2, if possible a help will be useful.

**Comment by elyast** [comment]
found the root cause, spark 2.1 added new method to the interface:
`org.apache.spark.sql.execution.datasources.OutputWriterFactory#def getFileExtension(context: TaskAttemptContext): String`

which is not implemented in spark-avro, hence AbstractMethodError

**Comment by apurva-sharma** [comment]
Ran into the same issue with spark 2.1.0 , is there a work around (besides bumping the spark version down?).

**Comment by elyast** [comment]
@apurva-sharma you can build this patch: https://github.com/databricks/spark-avro/pull/206 and replace spark-avro dependency with this custom version, at least it worked for us

**Comment by apurva-sharma** [comment]
@elyast thanks for that, I can verify that monkey patching spark-avro as above worked for me with spark 2.1.0
It will be great if this is merged.

**Comment by elyast** [comment]
@apurva-sharma +1

**Comment by alexander-branevskiy** [comment]
looks like spark-avro was fixed. any updates here?

**Comment by sanketvega** [comment]
any updates when this issue will be fixed?

**Comment by diegorep** [comment]
^ @JoshRosen

**Comment by girlonrails** [comment]
Atm this driver is completely unusable ...

**Comment by hnfmr** [comment]
Fixed mine by adding this line to sbt project build.sbt:

`    dependencyOverrides += spark_avro_320
`
where
`  val spark_avro_320: ModuleID = "com.databricks" % "spark-avro_2.11" % "3.2.0"`

I am using spark-redshift 3 btw...

Hopefully this library can be actively supported in the long run, it looks like it has not been updated for several months....

**Comment by mrdmnd** [comment]
I've tried what @hnfmr suggests, but I am still running into this issue.

**Comment by hnfmr** [comment]
@mrdmnd To be specific, I am using the Spark-Redshift v3.0.0-preview1 and my `build.sbt` looks like:
```
lazy val app = (project in file("app")).
  .settings(commonSettings: _*)
  .settings(
    libraryDependencies += "com.databricks" % "spark-redshift_2.11" % "3.0.0-preview1",
    dependencyOverrides += "com.databricks" % "spark-avro_2.11" % "3.2.0"
  )
)
```
BTW, I am using Spark 2.1.0... hope this helps

**Comment by wafisher** [comment]
@elyast Can you please describe what you did? My guess:

1. Clone the `spark-avro` repo and checkout the commit of that PR (post-merge).
2. Build the jar.
3. Use SBT to use this jar. (Do you know how to do this offhand?)

Thank you!

**Comment by sadowski** [comment]
Also seeing this issue here. @hnfmr's fix is working for me now, but it would be nice to have this properly fixed. Spark is a popular tool and Redshift usage is only going to grow.

Exact workaround was to add the following to my build.sbt file:
```
// Temporary fix for: https://github.com/databricks/spark-redshift/issues/315
dependencyOverrides += "com.databricks" % "spark-avro_2.11" % "3.2.0"
```

**Comment by mrdmnd** [comment]
Yeah, I had a minor typo. Can confirm that this works.

**Comment by cockroachzl** [comment]
I use Zeppelin to do ETL to redshift and encountered the same AbstractMethodError. 

By configuring the spark interpreter to exclude `com.databricks:spark-avro_2.11:3.0.0` while depending on `com.databricks:spark-redshift_2.11:2.0.1`, and then to specify another dependency on `com.databricks:spark-avro_2.11:3.2.0` works for me

Thanks a lot!

**Comment by Aung-Myint-Thein** [comment]
Yes! Just update or replace spark-avro_2.11-3.1.0.jar with spark-avro_2.11-3.2.0.jar and this problem should be solved now.

https://mvnrepository.com/artifact/com.databricks/spark-avro_2.11/3.2.0

**Comment by cshintov** [comment]
HI, I have got the same problem.
I am using spark 2.1.0 and tried using spark-redshift 3.0.0-preview1 and 2.0.1, 2.0.0. All of them gives the same error.

java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/T$
skAttemptContext;)Ljava/lang/String;
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeT$
sk(FileFormatWriter.scala:182)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/04/24 21:12:15 ERROR TaskSetManager: Task 1 in stage 2.0 failed 1 times; aborting job
17/04/24 21:12:15 ERROR FileFormatWriter: Aborting job null.
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in s
tage 2.0 (TID 202, localhost, executor driver): java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.
getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTa
sk(FileFormatWriter.scala:182)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by giaosudau** [comment]
I have the same problem and I am using code in spark branch 2.2. Spark avro was spark-avro_2.11-3.2.0.jar already.

```
Caused by: java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriter.write(Lorg/apache/spark/sql/catalyst/InternalRow;)V
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:318)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:249)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:247)
  at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:252)
```

**Comment by davidzhao** [comment]
Any updates on this one? It seems that the underlying dependency (spark-avro_2.11-3.2.0) has resolved this issue. Instead of having everyone depend on the workaround, could the owner release a version that depends on the 3.2.0 of spark-avro?

**Comment by schwartzmx** [comment]
It seems this issue and repo are getting stale,  would love to have this updated.   @JoshRosen would it be possible to open this up to new contributors?

**Comment by tylermichael** [comment]
Any updates on this? I'm using this through pyspark and am unable to try the work arounds suggested.

**Comment by dnaumenko** [comment]
Looks like this issue is going to be fixed in next version of spark-avro lib - https://github.com/databricks/spark-avro/pull/242. It's merged to master 8 days ago

**Comment by pmatpadi** [comment]
Thanks for the hint on updating spark-avro dependency version. 

I resolved this issue with below spark-submit command in AWS EMR environment:
spark-submit --deploy-mode cluster --class <main_class> --packages com.databricks:spark-redshift_2.11:3.0.0-preview1,com.databricks:spark-avro_2.11:3.2.0,com.amazon.redshift:redshift-jdbc42:1.2.8.1005 --repositories http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release s3://<path_to_my_spark_application_jar>

**Comment by marcintustin** [comment]
I've updated to spark-avro 4.0.0 and I still have this issue.

**Comment by zhassanbey** [comment]
I have faced the same exception with spark_2.11 v2.1.1.
The reason was that my project depended on a custom library which in turn depended on spark-avro v4.0.0 artifact in 'compileOnly' scope. Therefore the spark-avro dependency wasn't really propagating to my project. After I added spark-avro v4.0.0 dependency explicitly the problem resolved.

**Comment by schwartzmx** [comment]
I wouldn't expect this to be _properly_ fixed,  it seems databricks has decided to not update this library anymore *outside* of their own Databricks Runtime which as far as I can tell requires you to be using their entire platform, https://github.com/databricks/spark-redshift/commit/717a4ad622cc03e7f8a74bbf199332699a826ff5#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Renien** [comment]
@hnfmr Thanks for the hint. Even I faced the same issue while running ALS model in GCP and storing the output using com.databricks.spark.csv. Initially I was using com.databricks.spark.csv - 1.2.0 with Spark 2.2.0 and issue occurred. I've updated with latest version 1.5.0 and solved my issue.

**Comment by yggowda** [comment]
I was using older version of spark-redshift_2.11 changed to 3.0.0..preview and it started working

**Comment by schwartzmx** [comment]
If anyone is still having issues and wants to collab on this,  I forked both this connector and spark-avro,  we can get a working group around fixing these.   I think this library & spark-avro are dead  from an open-source continued support/contributor perspective (outside of the Databricks Runtime https://github.com/databricks/spark-redshift/commit/717a4ad622cc03e7f8a74bbf199332699a826ff5#diff-04c6e90faac2675aa89e2176d2eec7d8) as the last commits are 2+ years old aside from README updates.   

We would be required to adhere to the licensing (Apache 2.0),  via NOTICE and some other means.
If interested in some collab/updates,  email me @schwartzmx@gmail.com 

Love the library @databricks but many people use this connector and library,  I asked if this could be opened up to collaborators and didn't hear a response in over a year.   It seems like it was quietly moved to closed source,  which is understandable.. from a business perspective.

Thanks for all the initial work on this,  has helped a ton of people out to begin with and I personally have built many ETLs and data analysis tools from using this connector.

Cheers,
Phil
