### ISSUE TITLE
Spark 2.2 Abstract Method Error

### ISSUE THREAD

**Issue by autodidacticon** [databricks/spark-redshift#360]
Using spark-avro 3.2.0 as suggested in #315 

Receiving the follow error:
```
java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriter.write(Lorg/apache/spark/sql/catalyst/InternalRow;)V
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:327)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:258)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:256)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:261)
```

**Comment by dnaumenko** [comment]
As a temporary fix, you can build spark-avro from master branch (as the fix is not released yet) and add it to your assembly jar as unmanaged dependency.

**Comment by geek311** [comment]
Built spark-avro from master branch and got spark-avro-assembly-4.0.0-SNAPSHOT.jar and on adding that in sbt as > set unmanagedBase := file("...")
I see the snapshot jar in the jar dependencies list. Transported my jar and the dependencies jars to cluster.
I am doing a fat jar with scala 2.11.8
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.12.0")

However on spark submitting with the --jars option i am getting the LinkageError
Warning: Ignoring non-spark config property: #spark.executor.cores=5
Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.spark.streaming.StreamingContext$.getOrCreate(Ljava/lang/String;Lscala/Function0;Lorg/apache/hadoop/conf/Configuration;Z)Lorg/apache/spark/streaming/StreamingContext;" the class loader (instance of org/apache/spark/util/ChildFirstURLClassLoader) of the current class and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/spark/streaming/StreamingContext$, have different Class objects for the type scala/Function0 used in the signature

**Comment by bvpatel** [comment]
Please use spark-avro 4.0.0
