### ISSUE TITLE
Failed to Read columns with type Timestamp with timezone

### ISSUE THREAD

**Issue by chuangliuconvoy** [databricks/spark-redshift#391]
I have a redshift table column with type "Timestamp with timezone". When I tried to use Spark to write this table to a file, I got the following error. Because the column in redshift is in the format of "2017-07-13 18:54:10.441+00",  Spark-Redshift failed to parse it because it uses java.sql.Timestamp.valueOf(), and this function cannot handle the "+00" at the end of timestamp string. How should I get around the issue ? Thanks

java.lang.NumberFormatException: For input string: "249+00000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.sql.Timestamp.valueOf(Timestamp.java:255)
	at com.databricks.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:100)
	at com.databricks.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:100)
	at com.databricks.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:112)
	at com.databricks.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:108)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:170)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:391)

**Comment by dichiarafrancesco** [comment]
would it work casting explicitly those columns into timestamp without timezone in the sql query? 

something like:
`SELECT timestampz_column::TIMESTAMP, other_column, ....`
