### ISSUE TITLE
NPE on lifecycle rule check

### ISSUE THREAD

**Issue by cfeduke** [databricks/spark-redshift#91]
While this is just a logger WARN message the stack trace caught me by surprise at first and I was trying to hunt down the cause of the error:

```scala
> df.first()
2015-09-18 08:10:59,269 [main                 | WARN ] com.databricks.spark.redshift.Utils$ - An error occurred while trying to read the S3 bucket lifecycle configuration
java.lang.NullPointerException
        at com.databricks.spark.redshift.Utils$$anonfun$1.apply(Utils.scala:80)
        at com.databricks.spark.redshift.Utils$$anonfun$1.apply(Utils.scala:76)
```

I am using `com.amazonaws:aws-java-sdk-s3:1.10.8:jar` in production. I have a rule on my bucket named `delete-after-1-day` which does exactly what the rule name suggests.

**Comment by JoshRosen** [comment]
Judging from the stacktrace, it looks like our code didn't guard against `key` being null: https://github.com/databricks/spark-redshift/blob/v0.5.0/src/main/scala/com/databricks/spark/redshift/Utils.scala#L80

Let me see if there's a quick fix for this.
